import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {allTracks,db,getSetting,isOwner,mustOwner,runtime,sameOrigin,settings,stripe,textValue} from '@/lib/server';
export const dynamic='force-dynamic';
const json=(x:unknown,status=200)=>Response.json(x,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(req:Request){try{const url=new URL(req.url);const action=url.searchParams.get('action');
if(action==='media'){const key=url.searchParams.get('key')||'';if(!key.startsWith('public/'))return json({error:'Not found'},404);const f=await env.BUCKET?.get(key);if(!f)return json({error:'Not found'},404);return new Response(f.body,{headers:{'Content-Type':f.httpMetadata?.contentType||'application/octet-stream','Cache-Control':'public, max-age=3600','X-Content-Type-Options':'nosniff'}})}
if(action==='download'){const sid=url.searchParams.get('session')||'';if(!/^cs_(test_|live_)?[a-zA-Z0-9_]+$/.test(sid))return json({error:'Invalid order'},400);const session=await stripe('checkout/sessions/'+sid);const order=await db().prepare('SELECT * FROM orders WHERE id=?').bind(sid).first<any>();if(!order||session.payment_status!=='paid'||session.amount_total!==order.amount||session.metadata?.store!=='johnny-speakers')return json({error:'Payment is not confirmed yet. Please retry after checkout.'},403);if(url.searchParams.get('license')==='1')return new Response(order.title+'\nOrder '+sid+'\n\n'+order.terms,{headers:{'Content-Type':'text/plain; charset=utf-8','Content-Disposition':'attachment; filename="JDP-license.txt"','Cache-Control':'no-store'}});const f=await env.BUCKET?.get(order.file_key);if(!f)return json({error:'Your file is unavailable. Contact JDP with your receipt.'},404);return new Response(f.body,{headers:{'Content-Type':f.httpMetadata?.contentType||'application/octet-stream','Content-Disposition':'attachment; filename="'+order.file_key.split('/').pop()+'"','Cache-Control':'private, no-store','Referrer-Policy':'no-referrer'}})}
const owner=await isOwner();const user=await getChatGPTUser();const tracks=await allTracks();const posts=await db().prepare('SELECT id,name,kind,body,rating,parent,created FROM posts WHERE approved=1 ORDER BY created DESC LIMIT 150').all();const common={tracks:tracks.map(({master,...t})=>({...t,available:!!master&&!!t.terms&&t.enabled&&!!runtime().STRIPE_SECRET_KEY})),settings:await settings(),posts:posts.results,user:user?{name:user.fullName||'Music fan'}:null,owner,claimed:!!await getSetting('owner'),payments:!!runtime().STRIPE_SECRET_KEY};
if(action==='admin'){if(!owner)return json({...common},200);const [inquiries,pending]=await Promise.all([db().prepare('SELECT * FROM inquiries ORDER BY created DESC LIMIT 100').all(),db().prepare('SELECT * FROM posts ORDER BY created DESC LIMIT 200').all()]);return json({...common,tracks,inquiries:inquiries.results,moderation:pending.results})}return json(common);
}catch(e){console.error(e);return json({error:e instanceof Error?e.message:'Store temporarily unavailable'},503)}}
export async function POST(req:Request){try{sameOrigin(req);const url=new URL(req.url);const action=url.searchParams.get('action');const user=await getChatGPTUser();
if(action==='upload'){await mustOwner();if(Number(req.headers.get('content-length')||0)>26*1024*1024)return json({error:'Please keep each upload under 25 MB.'},413);const form=await req.formData();const file=form.get('file');const kind=form.get('kind');if(!(file instanceof File)||file.size>25*1024*1024||!file.size)throw new Error('Choose a file up to 25 MB.');const allowed=kind==='master'?/\.(mp3|wav|zip)$/i:kind==='preview'?/\.(mp3|wav)$/i:/\.(jpg|jpeg|png|webp)$/i;if(!allowed.test(file.name))throw new Error('Unsupported file type.');const ext=file.name.split('.').pop()?.toLowerCase();const key=(kind==='master'?'private/':'public/')+crypto.randomUUID()+'.'+ext;const types:Record<string,string>={mp3:'audio/mpeg',wav:'audio/wav',zip:'application/zip',jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp'};await env.BUCKET!.put(key,file.stream(),{httpMetadata:{contentType:types[ext||'']||'application/octet-stream'}});return json({key,url:kind==='master'?key:'/api/store?action=media&key='+encodeURIComponent(key)})}
const b:any=await req.json();
if(action==='claim'){if(!user)return json({error:'Sign in with ChatGPT first.'},401);if(!runtime().OWNER_SETUP_CODE||b.code!==runtime().OWNER_SETUP_CODE)return json({error:'Incorrect studio setup code.'},403);const r=await db().prepare('INSERT OR IGNORE INTO settings (key,value) VALUES (?,?)').bind('owner',user.userId).run();if(!r.meta.changes&&await getSetting('owner')!==user.userId)return json({error:'This studio already has an owner.'},403);return json({ok:true})}
if(action==='settings'){await mustOwner();const next:Record<string,string>={};for(const key of ['phone','email','instagram','youtube','tiktok'])next[key]=textValue(b[key],300);if(next.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(next.email))throw new Error('Enter a valid email.');for(const key of ['instagram','youtube','tiktok']){if(next[key]){const u=new URL(next[key]);if(u.protocol!=='https:')throw new Error('Social links must start with https://')}}await db().prepare('INSERT INTO settings (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('public',JSON.stringify(next)).run();return json({ok:true})}
if(action==='track'){await mustOwner();const t={id:textValue(b.id,100)||crypto.randomUUID(),title:textValue(b.title,100),genre:textValue(b.genre,80),description:textValue(b.description,600),preview:textValue(b.preview,500),cover:textValue(b.cover,500),master:textValue(b.master,250),price:Number(b.price),terms:textValue(b.terms,10000),enabled:b.enabled===true};if(!t.title||!Number.isFinite(t.price)||t.price<1||t.price>10000)throw new Error('Enter a title and price between $1 and $10,000.');if(t.master&&!/^private\/[a-zA-Z0-9._-]+$/.test(t.master))throw new Error('Upload the delivery file in the studio.');for(const k of ['preview','cover'] as const){if(t[k]&&!t[k].startsWith('/media/')&&!t[k].startsWith('/api/store?action=media&key=public'))throw new Error('Use a studio upload for media.')}if(t.enabled&&(!t.master||!t.terms||!t.preview))throw new Error('Add a preview, delivery file and license terms before enabling sales.');await db().prepare('INSERT INTO tracks (id,data) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(t.id,JSON.stringify(t)).run();return json({ok:true})}
if(action==='moderate'){await mustOwner();if(b.remove)await db().prepare('DELETE FROM posts WHERE id=?').bind(textValue(b.id,100)).run();else await db().prepare('UPDATE posts SET approved=? WHERE id=?').bind(b.approved?1:0,textValue(b.id,100)).run();return json({ok:true})}
if(action==='checkout'){const t=(await allTracks()).find(t=>t.id===b.id);if(!t||!t.enabled||!t.master||!t.terms||!runtime().STRIPE_SECRET_KEY)throw new Error('This beat is preview-only. Contact JDP for availability.');if(!await env.BUCKET?.head(t.master))throw new Error('The delivery file is unavailable. No payment was taken.');const origin=runtime().SITE_URL||url.origin;const p=new URLSearchParams({mode:'payment','payment_method_types[0]':'card','line_items[0][price_data][currency]':'usd','line_items[0][price_data][unit_amount]':String(Math.round(t.price*100)),'line_items[0][price_data][product_data][name]':t.title+' — JDP license','line_items[0][quantity]':'1',success_url:origin+'/success?session_id={CHECKOUT_SESSION_ID}',cancel_url:origin+'/?cancelled=1','metadata[store]':'johnny-speakers','metadata[track]':t.id});const s=await stripe('checkout/sessions',p);await db().prepare('INSERT INTO orders (id,track_id,file_key,title,terms,amount) VALUES (?,?,?,?,?,?)').bind(s.id,t.id,t.master,t.title,t.terms,Math.round(t.price*100)).run();return json({url:s.url})}
if(!user)return json({error:'Please sign in with ChatGPT to submit.'},401);
const body=textValue(b.body);const name=textValue(b.name,80)||user.fullName||'Music fan';if(body.length<5)throw new Error('Please write at least 5 characters.');
if(action==='post'){const recent=await db().prepare('SELECT created FROM posts WHERE user_id=? AND created>? LIMIT 1').bind(user.userId,Date.now()-30000).first();if(recent)throw new Error('Please wait 30 seconds before posting again.');const kind=['review','request','discussion','reply'].includes(b.kind)?b.kind:'discussion';const rating=kind==='review'?Number(b.rating):null;if(kind==='review'&&(!Number.isInteger(rating)||rating!<1||rating!>5))throw new Error('Choose a rating from 1 to 5.');const parent=textValue(b.parent,100)||null;if(parent&&!await db().prepare('SELECT id FROM posts WHERE id=? AND approved=1').bind(parent).first())throw new Error('That conversation is unavailable.');await db().prepare('INSERT INTO posts (id,user_id,name,kind,body,rating,parent,created,approved) VALUES (?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),user.userId,name,kind,body,rating,parent,Date.now(),await isOwner()?1:0).run();return json({ok:true,message:'Thanks! Your post will appear after review.'})}
if(action==='inquiry'){const email=textValue(b.email,250);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('Enter a valid reply email.');const recent=await db().prepare('SELECT id FROM inquiries WHERE user_id=? AND created>? LIMIT 1').bind(user.userId,Date.now()-30000).first();if(recent)throw new Error('Please wait 30 seconds before sending another message.');await db().prepare('INSERT INTO inquiries (id,user_id,name,email,kind,body,created) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),user.userId,name,email,textValue(b.kind,50),body,Date.now()).run();return json({ok:true,message:'Your message is in JDP’s studio inbox.'})}return json({error:'Unknown action'},400);
}catch(e){console.error(e);return json({error:e instanceof Error?e.message:'Unable to save. Please try again.'},400)}}
